export const products = [
  {
    id: 0,
    images: [
      '/images/lips-01.png',
      '/images/lips-02.png',
      '/images/lips-03.png',
      '/images/lips-04.png',
    ],
    title: 'Подставка для благовоний Lips',
    body: 'Подставка для благовоний Lips',
    material: 'Гипс',
    dimensions: '11,5см x 2,5см',
    color: 'Белый, черный',
    price: '600',
  },
  {
    id: 1,
    images: [
      '/images/square-01.png',
      '/images/square-02.png',
      '/images/square-03.png',
      '/images/square-04.png',
    ],
    title: 'Подсвечник Square',
    body: 'Подсвечник Square',
    material: 'Гипс',
    dimensions: '9,5см х 9,5см х 1,5см',
    color: 'Белый, черный',
    price: '400',
  },
  {
    id: 2,
    images: [
      '/images/rectangle-01.png',
      '/images/rectangle-02.png',
      '/images/rectangle-03.png',
      '/images/rectangle-04.png',
    ],
    title: 'Подставка Rectangle',
    body: 'Подставка Rectangle',
    material: 'Гипс',
    dimensions: '17см х 8см х 1см',
    color: 'Белый',
    price: '400',
  },
  {
    id: 3,
    images: [
      '/images/dinner-01.png',
      '/images/dinner-02.png',
      '/images/dinner-03.png',
      '/images/dinner-04.png',
    ],
    title: 'Подсвечник Dinner 2шт.',
    body: 'Подсвечник Dinner 2шт.',
    material: 'Гипс',
    dimensions: '5см х 6см',
    color: 'Белый, мрамор',
    price: '400',
  },
  {
    id: 4,
    images: [
      '/images/lips-01.png',
      '/images/lips-02.png',
      '/images/lips-03.png',
      '/images/lips-04.png',
    ],
    title: 'Подставка для благовоний Lips',
    body: 'Подставка для благовоний Lips',
    material: 'Гипс',
    dimensions: '11,5см x 2,5см',
    color: 'Белый, черный',
    price: '600',
  },
  {
    id: 5,
    images: [
      '/images/square-01.png',
      '/images/square-02.png',
      '/images/square-03.png',
      '/images/square-04.png',
    ],
    title: 'Подсвечник Square',
    body: 'Подсвечник Square',
    material: 'Гипс',
    dimensions: '9,5см х 9,5см х 1,5см',
    color: 'Белый, черный',
    price: '400',
  },
  {
    id: 6,
    images: [
      '/images/rectangle-01.png',
      '/images/rectangle-02.png',
      '/images/rectangle-03.png',
      '/images/rectangle-04.png',
    ],
    title: 'Подставка Rectangle',
    body: 'Подставка Rectangle',
    material: 'Гипс',
    dimensions: '17см х 8см х 1см',
    color: 'Белый',
    price: '400',
  },
  {
    id: 7,
    images: [
      '/images/dinner-01.png',
      '/images/dinner-02.png',
      '/images/dinner-03.png',
      '/images/dinner-04.png',
    ],
    title: 'Подсвечник Dinner 2шт.',
    body: 'Подсвечник Dinner 2шт.',
    material: 'Гипс',
    dimensions: '5см х 6см',
    color: 'Белый, мрамор',
    price: '400',
  },
]

export const social = [
  {
    id: 1,
    name: 'instagram',
    href: '#',
  },
  {
    id: 2,
    name: 'telegram',
    href: '#',
  },
  {
    id: 3,
    name: 'whatsapp',
    href: '#',
  },
]
